import { pgTable, uuid, text, timestamp, integer, boolean, index } from 'drizzle-orm/pg-core'
import { sql } from 'drizzle-orm'

/**
 * Sessions table - tracks all photobooth sessions
 * 
 * Stores session metadata including:
 * - Event information
 * - Photo capture details
 * - User actions (downloads, exports, QR scans)
 * - Template selection
 */
export const sessions = pgTable('sessions', {
  // Primary key - UUID generated by PostgreSQL
  id: uuid('id')
    .primaryKey()
    .default(sql`gen_random_uuid()`),
  
  // Event metadata
  eventName: text('event_name'),
  footerText: text('footer_text'),
  
  // Timestamps
  createdAt: timestamp('created_at', { mode: 'date' })
    .notNull()
    .default(sql`NOW()`),
  
  // Photo session details
  photosTaken: integer('photos_taken')
    .notNull()
    .default(4),
  
  sessionDuration: integer('session_duration'), // in seconds
  
  // Template selection
  templateId: text('template_id'),
  
  // User action tracking (boolean flags)
  downloaded: boolean('downloaded')
    .notNull()
    .default(false),
  
  pdfExported: boolean('pdf_exported')
    .notNull()
    .default(false),
  
  qrScanned: boolean('qr_scanned')
    .notNull()
    .default(false),
}, (table) => ({
  // Indexes for common query patterns
  createdAtIdx: index('idx_sessions_created_at').on(table.createdAt),
  eventNameIdx: index('idx_sessions_event_name').on(table.eventName),
  templateIdIdx: index('idx_sessions_template_id').on(table.templateId),
}))
